// <auto-generated />
namespace MoviesApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addMovieGenref6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addMovieGenref6));
        
        string IMigrationMetadata.Id
        {
            get { return "202008031057292_addMovieGenref6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
